version: '3.8'

services:
  web:
    build: .  # Uses the Dockerfile in the current directory
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=orders.settings
      - DATABASE_URL=postgres://postgres:password@db:5432/orders_db # Updated
      - ALLOWED_HOSTS=localhost,127.0.0.1,.localhost,0.0.0.0 # Allow all hosts in development
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media


  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=orders_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis: # Add Redis service
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A orders worker -l info
    environment:
        - DJANGO_SETTINGS_MODULE=orders.settings
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0

    depends_on:
      - redis
      - db



volumes:
  postgres_data:
  static_volume:
  media_volume:


